
spring:
 application:
   name: greeting-service

server:
 port: 8080
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka

app:
 greetingService:
  serviceId: greeting-service
  endpoint:
   greeting: /greeting
